### ISSUE TITLE
Update for sourcemod and new feature "nades per team"

### ISSUE THREAD

**Issue by BrutalCSEjziponken** [BatMen/csgo-retakes-splewis-convar-weapon-allocator#5]
/csgo/addons/sourcemod/scripting/include/smlib/entities.inc(33) : error 138: const was specified twice

/csgo/addons/sourcemod/scripting/include/smlib/crypt.inc(426) : error 173: 'in' is a newly reserved keyword that may be used in the future; use a different name as an identifier

/csgo/addons/sourcemod/scripting/include/smlib/effects.inc(158) : warning 237: coercing functions to and from primitives is unsupported and will be removed in the future
retakes_standardallocator.sp(123) : error 180: function return type differs from prototype. expected 'void', but got 'int'

3 Errors.

**Comment by BatMen** [comment]
I'm going to release a new update. I will compare files and take updates from splewis official csgo-retakes plugin.

**Comment by BatMen** [comment]
This will resolve errors from retakes_standardallocator.sp but not the others. Thank you for the feedback.

**Comment by BrutalCSEjziponken** [comment]
Seems like smlib has an update that might fix my errors.
https://github.com/bcserv/smlib/commit/4f51b911f68fe37751c93c5e9d1909114f3e5b3e

Also one small request if you gonna update your plugin. Some players complains about how many smokes T/CT can have so maybe a way to limit it to 1 per team? Just a suggestion! :)

**Comment by BatMen** [comment]
The update will replace all the **weapon_nades_..._enabled** by **weapon_nades_..._max**

**Comment by RavageCS** [comment]
Would it be possible for player to have a choice of gear they get on pistol rounds instead of random?

Select what ever gear/nades you want as long as it is under $800.

For example you could set your gear with !pistol, then you could pick kit, flash, flash etc

Thanks for uploading sorry to tag along with this issue.

**Comment by BatMen** [comment]
Hello,

I'm waiting for a server with people on it to do more tests but the update is finished. I may deliver a beta release soon... (today?)

This is a good suggestion, but it needs time for test and i find 1 issue with this : 
Ask too much questions to the player. There are already 3 questions : Pistol, M4 and AWP. 

It would be nice to use the inventory choice of the player for M4. Splewis didn't make it like this, I think this is because it's different than pistols slot.... If I reach to find time and to remove this question, maybe I would ask for nades/equipment choice after pistol choice.

My problem for now is the lack of tests I can do on a working server with people to release updates more often.

**Comment by BatMen** [comment]
*Also one small request if you gonna update your plugin. Some players complains about how many smokes T/CT can have so maybe a way to limit it to 1 per team? Just a suggestion! :)*

**This is done in the new beta release.**
